### ISSUE TITLE
Primary key with autogenerate: false is not mapped to mongo's _id field

### ISSUE THREAD

**Issue by ivoanjo** [ankhers/mongodb_ecto#65] opened 2016-01-21 16:05 UTC
Normally, mongodb_ecto maps the declared `primary_key` to the mongo `_id` field:

``` elixir
defmodule Weather do
  use Ecto.Model

  @primary_key {:id, :binary_id, autogenerate: true}

  schema "weather" do
    field :city, :string
    field :temp_lo, :integer
    field :temp_hi, :integer
    field :prcp, :float, default: 0.0
    timestamps
  end
end
```

so both of these are valid:

``` elixir
  test "(Weather) id with autogenerate: true and not specifying id" do
    inserted = Simple.Repo.insert! %Weather{}

    assert Simple.Repo.get(Weather, inserted.id) == inserted
  end

  test "(Weather) id with autogenerate: true and specifying id" do
    inserted = Simple.Repo.insert! %Weather{id: "56a01f800000000000000001"}

    assert Simple.Repo.get(Weather, inserted.id) == inserted
  end
```

but whenever `autogenerate` is set to `false`, `mongodb_ecto` just ignores the configured primary key, and just adds its own autogenerated `_id`, adding the configured primary key field as just another field, and breaking searches by primary key:

``` elixir
defmodule WeatherFoo do
  use Ecto.Model

  @primary_key {:id, :binary_id, autogenerate: false}

  schema "weatherfoo" do
    field :city, :string
    field :temp_lo, :integer
    field :temp_hi, :integer
    field :prcp, :float, default: 0.0
    timestamps
  end
end

  test "(WeatherFoo) id with autogenerate: false and specifying id" do
    inserted = Simple.Repo.insert! %WeatherFoo{id: "56a01f800000000000000002"}

    assert Simple.Repo.get(WeatherFoo, inserted.id) == inserted # (Does NOT work, the get returns nil)
  end
```

In this case, if we look in mongo we'll find this document:

``` elixir
{
    "_id" : ObjectId("1e33b860dd1c0d0a390985cb"),
    "inserted_at" : ISODate("2016-01-21T15:40:16.000Z"),
    "updated_at" : ISODate("2016-01-21T15:40:16.000Z"),
    "city" : null,
    "id" : ObjectId("56a01f800000000000000002"),
    "prcp" : 0.0000000000000000,
    "temp_hi" : null,
    "temp_lo" : null
}
```

This basically breaks any case we want to generate custom keys, especially in the case where we want to use plain strings instead of ObjectIds (for compatibility with other strings), and in general is quite unexpected as the only thing that changed is that we said that ecto should not autogenerate an `id` when none is received.

[Runnable testcase: primary-key-autogenerate-testcase.zip](https://github.com/michalmuskala/mongodb_ecto/files/99382/primary-key-autogenerate-testcase.zip)

**Comment by scottmessinger** [comment] 2016-03-15 02:59
I also ran into this! Really great writeup @ivoanjo!

The specific line that's at the start of the problem seems to be here:
https://github.com/michalmuskala/mongodb_ecto/blob/master/lib/mongo_ecto.ex#L507
```elixir
  def insert(repo, meta, params, nil, [], opts) do
    normalized = NormalizedQuery.insert(meta, params, nil)
```

This line is called by Ecto:
https://github.com/elixir-lang/ecto/blob/v1.0/lib/ecto/adapter.ex#L155
```elixir
defcallback insert(repo, model_meta, fields, autogenerate_id, returning, options) 
```

If the `id` has been autogenerated, the `id` is passed to the insert of `nil`. The insert callback sends `nil` through the `normalized_query` module which calls the `conversion` module which is responsible for converting `id` to `_id`. That conversion never happens because the following line is never called:
https://github.com/michalmuskala/mongodb_ecto/blob/master/lib/mongo_ecto/conversions.ex#L72

```elixir
  defp key(pk, pk), do: :_id
```

Instead, the following line is called which leads to `id` never being converted to `_id` which causes the problem @ivoanjo illustrated above

```elixir
  defp key(key, _), do: key
```

I'm not sure if the solution to the problem is in Ecto or in this library, but if we can find a way to change [mongo_ecto.ex#L507](https://github.com/michalmuskala/mongodb_ecto/blob/master/lib/mongo_ecto.ex#L507) so we send a primary key through the rest of the code paths, the problem *should* be fixed (from as far as I can tell). Also, the callback signature changed a bit in ecto 2.0 so I'm unsure the best way to proceed.

I'd be happy to help out with a patch! Any ideas on how to address this @michalmuskala @ericmj?

PS. The problem can be worked around by making the primary key for a schema be `_id`

**Comment by Morganjackson** [comment] 2016-12-07 22:41
@scottmessinger Could you please provide a example of your workaround?

I have an existing database that uses strings`"TWhmtZAFWaxo85NHP"` for id's but so far everything I have tried results in `ObjectId("58488cb875e973b41878102a")` which obviously isn't compatible.

**Comment by iStefo** [comment] 2016-12-07 22:46
If I may weight in on this (since I had the same problem and also fixed it by making the PK `_id`):

Model (Ecto 2 syntax):
```ex
  @required [:_id]
  @primary_key {:_id, :string, autogenerate: false}

  #...
  
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @required ++ @optional)
    |> validate_required(@required)
    |> unique_constraint(:_id, name: :_id_)
  end
```

Then, when working with records, I always refer to the PK as `_id`, as in `%Model{_id: ... }`.
Not the nicest solution, but it works and is similar to how you use mongodb's `_id` field in other languages.

**Comment by Morganjackson** [comment] 2016-12-08 03:59
Thanks Stefan! what do you use to generate the _id?

**Comment by iStefo** [comment] 2016-12-08 08:49
@Morganjackson I use an optimistic insert loop (idea taken from https://docs.mongodb.com/v3.0/tutorial/create-an-auto-incrementing-field/#optimistic-loop) and a function that generates ID strings with a low probability of collisions (~70mio IDs to choose from).

```ex
defmodule BxWebrtc.ChannelController do
  @max_tries 10

  @spec create_channel(%{}, pos_integer()) :: {:ok, BxWebrtc.Channel} | {:error, Strong.t} 
  def create_channel(%{ owner: _ } = params, attempt \\ 1) do
    random_id = generate_random_id()
    channel = BxWebrtc.Channel.changeset(%BxWebrtc.Channel{}, Map.merge(params, %{
      _id: random_id
    }))

    case BxWebrtc.Repo.insert(channel) do
      {:ok, channel} -> {:ok, channel}
      
      # ID collision, but retry limit not exceeded
      {:error, %Ecto.Changeset{errors: [_id: _]}} when attempt < @max_tries -> 
        _ = Logger.info "ChannelController: retry channel insert \"#{random_id}\", attempt \##{attempt}"
        create_channel(params, attempt + 1)

      # ID collision, but max tries exceeded
      {:error, %Ecto.Changeset{errors: [_id: _]}} ->
        _ = Logger.error "ChannelController: unable to insert channel after #{attempt} attempts"
        {:error, "max_tries_exceeded"}

      e ->
        _ = Logger.error "ChannelController: error inserting channel: #{inspect(e)}"
        {:error, "database error"}
    end
  end

  defp generate_random_id(), do: BxWebrtc.FancyIds.generate()
end
```

**Comment by ankhers** [comment] 2017-11-27 15:57
I am going to close this as I believe it is for a version of the adapter that is no longer maintained. Please feel free to reopen or open another ticket if this is still an issue on either the `ecto-2` or `ecto-2.1` branches.

**Closed by ankhers** 2017-11-27 15:57 UTC
